# Enable only the Markdown linter
ENABLE:
  - MARKDOWN

# Customize specific Markdown linter rules
MARKDOWN_MD001: true  # Header levels should only increment by one level at a time
MARKDOWN_MD003:
  style: atx  # Header style (atx: # Header, setext: Header\n===)
MARKDOWN_MD004: true  # Unordered list style
MARKDOWN_MD009: true  # Trailing spaces
MARKDOWN_MD013:  # Line length
  line_length: 80
MARKDOWN_MD024: true  # Multiple headers with the same content
MARKDOWN_MD025: true  # Multiple top-level headers in the same document
MARKDOWN_MD031: true  # Fenced code blocks should be surrounded by blank lines
MARKDOWN_MD041: true  # First line in a file should be a top-level header
