name: MegaLinter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"        

      - name: Run MegaLinter in Fix Mode
        uses: oxsecurity/megalinter@v7.13.0

        with:
          # Include only Markdown files
          FILTER_REGEX_INCLUDE: ".*\\.md$"
          # Exclude everything else
          FILTER_REGEX_EXCLUDE: ".*"
          # Enable automatic fixing
          AUTOMATIC_FIX: true

      - name: Commit and push changes if any fixed
        if: ${{ steps.megalinter.outputs.fixed == 'true' }}
        run: |
          # Determine the current branch
          PR_BRANCH=$(echo ${{ github.head_ref }} | sed -e 's/\(.*\)/\L\1/')
          if [ -z "$PR_BRANCH" ]; then
            echo "No PR branch detected, exiting..."
            exit 1
          fi
          git checkout $PR_BRANCH
          git add .
          git commit -m "Apply fixes from MegaLinter"
          git push origin $PR_BRANCH